---
encrypted: "{{ cloud_providers.ec2.encrypted }}"
ec2_vpc_nets:
  vpc_cidr: "{{ lookup('env', 'ALGO_VPC_CIDR') }}"
  subnet_a_cidr: "{{ lookup('env', 'ALGO_SUBNET_A_CIDR') }}"
  subnet_b_cidr: "{{ lookup('env', 'ALGO_SUBNET_B_CIDR') }}"
existing_eip: ""
