---
- name: Deploy the template
  cloudformation:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "{{ algo_region }}"
    template: roles/cloud-ec2/files/stack.yaml
    template_parameters:
      CodeName: "{{ lookup('env', 'CODENAME') }}"
      InstanceTypeParameter: "{{ lookup('env', 'INSTANCE_TYPE') }}"
      PublicSSHKeyParameter: "{{ lookup('file', SSH_keys.public) }}"
      ImageIdParameter: "{{ ami_image }}"
      WireGuardPort: "{{ wireguard_port }}"
      UseThisElasticIP: "{{ existing_eip }}"
      EbsEncrypted: "{{ encrypted }}"
      UserData: "{{ lookup('template', 'files/cloud-init/base.yml') | b64encode }}"
      SshPort: "{{ ssh_port }}"
      VPCCidr: "{{ lookup('env', 'ALGO_VPC_CIDR') }}"
      SubnetACidr: "{{ lookup('env', 'ALGO_SUBNET_A_CIDR') }}"
      SubnetBCidr: "{{ lookup('env', 'ALGO_SUBNET_B_CIDR') }}"
    tags:
      Environment: Algo
  register: stack
